#!/bin/bash

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

if systemctl is-active sogo --quiet; then
    ynh_print_warn "It's hightly recommended to make your backup when the service is stopped. Please stop sogo service with this command before to run the backup 'systemctl stop sogo.service'"
fi

#=================================================
# SYSTEM CONFIGURATION
#=================================================

# Backup the nginx configuration
ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# BACKUP VARIOUS FILES
#=================================================

# Backup SOGo configuration
ynh_backup "/etc/$app"

# Backup cron
ynh_backup "/etc/cron.d/$app"

# Backup logs
ynh_backup "/var/log/$app"

#=================================================
# BACKUP THE MYSQL DATABASE
#=================================================
ynh_print_info "Backing up the MySQL database..."

ynh_mysql_dump_db > db.sql

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
