#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

# Check if the new path stay /SOGo if not exit
if [[ $path != "/SOGo" ]]; then
    ynh_die --message "You can't use an other path than '/SOGo'"
fi

#=================================================
# STANDARD MODIFICATIONS
#=================================================
ynh_script_progression --message="Updating NGINX configuration..."

ynh_change_url_nginx_config
config_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Change of URL completed for $app" --last
