#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

# Check if the new path stay /SOGo if not exit
if [[ $path != "/SOGo" ]]; then
    ynh_die  "You can't use an other path than '/SOGo'"
fi

#=================================================
ynh_script_progression "Updating NGINX configuration..."

ynh_config_change_url_nginx
config_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
