#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Removing system configurations related to $app..." --weight=1

yunohost service remove "sogo"

# Remove the dedicated systemd config
ynh_remove_systemd_config

# Remove the app-specific logrotate config
ynh_remove_logrotate

# Remove the dedicated NGINX config
ynh_remove_nginx_config

#=================================================
# SPECIFIC REMOVE
#=================================================
# REMOVE VARIOUS FILES
#=================================================
ynh_script_progression --message="Removing various files..." --weight=1

ynh_secure_remove --file="/etc/$app"

# Remove stunnel config
ynh_secure_remove --file="/etc/stunnel/$app.conf"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
