#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

yunohost service remove "sogo"

# Remove the dedicated systemd config
ynh_config_remove_systemd

# Remove the app-specific logrotate config
ynh_config_remove_logrotate

# Remove the dedicated NGINX config
ynh_config_remove_nginx

#=================================================
# SPECIFIC REMOVE
#=================================================
# REMOVE VARIOUS FILES
#=================================================
ynh_script_progression "Removing various files..."

ynh_safe_rm "/etc/$app"

# Remove stunnel config
ynh_safe_rm "/etc/stunnel/$app.conf"

if [ "$YNH_APP_PURGE" -eq 1 ]; then
    ynh_script_progression "Removing logs..."
    ynh_safe_rm /var/log/"$app"
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
