#!/bin/bash

# causes the shell to exit if any subcommand or pipeline returns a non-zero status
set -e

app=sogo

# The parameter $1 is the uncompressed restore directory location
backup_dir=$1/apps/$app

# Restore sources & data
sudo cp -a $backup_dir/sources/sogo.conf /etc/sogo/sogo.conf

# Restore permissions to app files
# you may need to make some file and/or directory writeable by www-data (nginx user)
sudo chown -R root:sogo /etc/sogo/sogo.conf

# Restore mysql database if needed
 db_pwd=$(sudo yunohost app setting $app mysqlpwd)
 sudo mysql -u $app -p$db_pwd $app < $backup_dir/$app.dmp

# Restore Nginx and YunoHost parameters
sudo cp -a $backup_dir/yunohost/. /etc/yunohost/apps/$app
domain=$(sudo yunohost app setting $app domain)
sudo cp -a $backup_dir/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# Restart webserver
sudo service nginx reload
sudo service sogo restart
